# Generated by Django 2.2.16 on 2022-06-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220627_0019'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='%(app_label)s_%(class)s_score_in_range_1_10',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='%(app_label)s_%(class)s_unique_title_author',
        ),
    ]
