# Generated by Django 2.2.16 on 2022-06-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220627_0207'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lt', 11)), name='%(app_label)s_%(class)s_score_in_range_1_10'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='%(app_label)s_%(class)s_unique_title_author'),
        ),
    ]
